### ISSUE TITLE
通过readme.md无法快速使用upload组件

### ISSUE THREAD

**Issue by Liboq** [l1uqi/draggable-vue-uploader#1]
![image](https://github.com/l1uqi/draggable-vue-uploader/assets/99778162/c2548737-244a-4ce8-874d-75d1cb3ef94e)
```js
<DraggableUploader /> 无法使用组件 需使用 <draggable-upload />
```
需完善readme😝

**Comment by l1uqi** [comment]
已添加

**Comment by l1uqi** [comment]
欢迎PR @Liboq
